services:

  api:
    build: .
    container_name: projeto-api

    ports:
      - "8000:8000"

    environment:
      DB_HOST: db
      DB_NAME: ragdb
      DB_USER: raguser
      DB_PASSWORD: ragpass
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

      OPENAI_API_KEY: k-	proj-3zr0sTt6tYM9R0JgKiHdu7gb6jgAAo1TErgH7ZAp20mllFH1O	QAGuqIOrr0icD6vPgNrlQ09O-T3BlbkFJ28Z32ok-	o5BP6fYtoixRJshaxwdwEx7z995Aj_tYYJ1O1xdtOSDkWBvXz2jcSq	MULGKgLN898A
      USE_REAL_API: "true"
      VECTORSTORE_PATH: data/vectorstore/faiss_index

    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

    restart: always


  db:
    image: ankane/pgvector:latest
    container_name: projeto-db

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: always


  redis:
    image: redis:6.2-alpine
    container_name: projeto-redis

    command: ["redis-server", "--save", "", "--appendonly", "no"]

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: always


  evolution-api:
    image: atendai/evolution-api:latest
    container_name: projeto-evolution-api

    ports:
      - "8080:8080"

    environment:
      AUTHENTICATION_API_KEY: "123456"

      # 🔥 Redis correto dentro do Docker
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # 🔥 FIX REAL (isso aqui resolve seu erro de disconnect)
      CACHE_REDIS_URI: redis://redis:6379/6

      # opcional (algumas versões usam isso também)
      CACHE_ENGINE: redis
      CACHE_ENABLED: "true"

      # banco
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://raguser:ragpass@db:5432/ragdb

    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

    restart: always

volumes:
  pgdata: