services:

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: ragdb
      DB_USER: raguser
      DB_PASSWORD: ragpass
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENAI_API_KEY: sua_chave

    depends_on:
      - db
      - redis

  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    ports:
      - "5433:5433"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"